### PR TITLE
Export pstream struct also to facilitate importing from a typed racke…

### PR DESCRIPTION
**Pull request by souravdatta**
…t program

Currently pstream struct is not imported and hence the same can not be used as a opaque type from a typed racket code (as pstream? predicate is not exported as well). This will allow to import inside TR as well.

### CODE REVIEW

**Comment by jbclements** [comment]
Ouch, I should have accepted this PR earlier. Now it has a (very simple) conflict. Can you rebase and fix this?

**Comment by souravdatta** [comment]
@jbclements conflict resolved.

**Comment by jbclements** [comment]
LGTM. Thanks!

**Comment by jbclements** [comment]
oops! didn't merge.

**Pull request merged**
